# vim: set ft=ansible et ts=2 sw=2:
# tasks file for ansible-role-liquidprompt
#
# Downloads and configures liquidprompt 
# https://github.com/nojhan/liquidprompt.git
#
---

- block:
    - name: Show connection and user to liquidify vars
      debug:
        msg: 'Connected as {{ ansible_user_id }}, going to liquidify {{ liquidprompt_user_to_liquidify }}.'

    - name: Clone liquidprompt repo to ~/lp
      git: 
        repo: '{{ liquidprompt_repo_url }}'
        version: '{{ liquidprompt_repo_version }}'
        dest: '~/lp'

    - name: Check to see if liquidprompt configuration file exists
      stat:
        path: "~/.liquidpromptrc"
      register: liquidpromptrc_file

    - name: Create liquidprompt configuration file if it doesn't exist
      copy:
        content: ""
        dest: "~/.liquidpromptrc"
        force: no
      when: not liquidpromptrc_file.stat.exists

    - name: Ensure liquidprompt lines are present in the configuration file
      lineinfile:
        path: "~/.liquidpromptrc"
        line: "{{ item }}"
        state: present
        backup: yes
      with_items:
        - "LP_HOSTNAME_ALWAYS=1"
        - "LP_ENABLE_TIME=1"

    - name: Add a line to .bashrc to source liquidprompt to start it
      lineinfile:
        path: "~/.bashrc"
        line: "[[ $- = *i* ]] && source ~/lp/liquidprompt"
        create: true
    
#    - name: Insert/update check to make .bash_profile call .bash_rc if running bash interactively
#      blockinfile:
#        path: "~/.bash_profile"
#        create: true
#        block: |
#          if [ -f ~/.bashrc ]; then
#                  . ~/.bashrc
#          fi
  become: true
  become_user: '{{ liquidprompt_user_to_liquidify }}'

